version: "3.8"

services:
  weather-db:
    image: mysql:8.0
    container_name: weather-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: weather_app
    ports:
      - "3306:3306"
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  weather-backend:
    build:
      context: ./WeatherDataFetcher
      dockerfile: Dockerfile
    container_name: weather-backend
    ports:
      - "8080:8080"
    depends_on:
      weather-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://weather-db:3306/weather_app?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
