version: "3.8"
services:
  weather-db:
    image: mysql:latest
    container_name: weather-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: weather_app
    ports:
      - "3306:3306"
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql
